### ISSUE TITLE
Knocked the model off the build plate

### ISSUE THREAD

**Issue by chrisl300** [awe-source/OctoPrint-SkipTo#3] opened 2024-08-31 16:30 UTC
I tried this because I had a print fail arounf 56%.
When it restarted it did a _home_ and then a purge line, which knocked the print off the bed. Then it tried to go to the correct re-start point and carry on printing, in mid-air.

**Comment by awe-source** [comment] 2024-08-31 20:19
Can you share the gcode?
If so we may be able to understand the purge line issue.

As for the re homing thing. It does this by design (or gcodes do... and we don't touch that bit).
However we do have todo that maybe worth adding.

Let us know thoughts on:

Skipping rehoming as an option (dangerous in some ways because if your print fails and the head is moved, at all, then the restart maybe "off" in space...)

Special refining of the rehoming so that the print heads is raised higher than the layer height... so in your case 56%+ ... then when the print heads moved to restart position it's going down not up...

Other ideas of how you'd like to see it function

**Comment by awe-source** [comment] 2024-08-31 23:45
Also perhaps it may be useful to have an option to start the first layer at a different speed...? Dunno if this is even possible... just a thought... 

But additionally while this may be possible and convenient in OctoPrint it might be "more sensible" to have these kinds of options INSIDE a plugin for a slicer...

Love to hear your thoughts

**Comment by chrisl300** [comment] 2024-09-01 21:38
Here's the gcode. I had deleted it but I recreated it as before. I think you said to someone else that if the nozzle was moved manually at all, it wouldn't work. This would be a problem because mine melted a hole in the model while I was trying to find a fix. I guess the lesson here is, don't mess with your cables while printing!

[CE3E3V2 Izettle_Dock SUNLU PLA lw 0.4mm lh 0.2mm if 10% ext1 210.0C bed 60C_skipTo_z-height_65.18.gcode.txt](https://github.com/user-attachments/files/16830576/CE3E3V2.Izettle_Dock.SUNLU.PLA.lw.0.4mm.lh.0.2mm.if.10.ext1.210.0C.bed.60C_skipTo_z-height_65.18.gcode.txt)

**Comment by awe-source** [comment] 2024-09-01 23:23
Thanks I’ll take a look
No that’s not quite right… in particular because of the melting issue( been there, done that!) there’s a … let’s say challenge… with the move no move thing and homing... 

I'll see what can be done... doesn't help you now I know, but maybe next time

**Comment by chrisl300** [comment] 2024-09-02 23:17
I currently have a print on my base that failed 7mm from the end. It is a wood PLA and the hot end became clogged. I would like to restart it, but at the moment I haven't got round to un-clogging the hot end, I think I'll have to dismantle it.
I've tried a wire brush and those acupuncture needles you get. Obviously I had to move the hot end to brush it, and more when I dismantle it.

I'm hoping to be able to restart it. Starting with a homing, but not a purge line because that will knock the model off the plate. Perhaps a filament change purge will do instead.
Maybe I am expecting too much.

The majority of the part that printed looks fantastic, but every time I have used wood PLA it has clogged before finishing.

**Comment by awe-source** [comment] 2024-09-03 00:50
This probably doesn't help you, but just thinking out loud here...

In this plug-in there is no option to not start printing immediately (but perhaps that's a good idea too for a next version.) but perhaps you can get the plug-in to do it magic and then stop the print immediately by killing the power or something before the head moves too fast too far.

And then you could download the code produced by the skip to and then manually modify it the first height move which should just be before Layer zero ...

And then maybe around that same area you might be able to identify where that purge line is coming from ...

Anyway, this is what we are looking at right now, but it's not gonna help you with that last 7 mm unless you've got plenty of time to wait for us

**Comment by awe-source** [comment] 2024-09-03 00:51
Also, yeah, the filaments with the "chunks" in it are notorious for clogging not just Wood the fibre ones as well from my experience... but they do look awesome.
 
Haven't tried myself but perhaps a larger mm nozzle might help?

Dunno what impact that has on other things tho

**Comment by chrisl300** [comment] 2024-09-03 06:45
I dismantled the hot end and replaced the nozzle.

I then tried using skip-to to produce the cut-down version of the Gcode, and then manually edited it to remove what I thought was the purge line code, then I loaded that back into Octoprint and tried to print, but it didn't work, it still tried to demolish the Japanese Brush Pot I was trying to print. So then I gave up!

**Comment by awe-source** [comment] 2024-09-07 12:54
Okay so 2 things.
1. just released a new version that has a few more bells and whistles that MAY make things better generally.
2.
with your gcode the 'scariest' bit is this:
G28 ; Home all axes
G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
G1 X0.1 Y20 Z0.3 F5000.0 ; Move to start position
G1 X0.1 Y200.0 Z0.3 F1500.0 E15 ; Draw the first line
G1 X0.4 Y200.0 Z0.3 F5000.0 ; Move to side a little
G1 X0.4 Y20 Z0.3 F1500.0 E30 ; Draw the second line
G92 E0 ; Reset Extruder
G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
G1 X5 Y20 Z0.3 F5000.0 ; Move over to prevent blob squish

and it all happens "before layer 1" (and I assume is "custom ender 3" stuff... given the comment)
but what really bothers me is the "draw the first line and second line..." bits... is it just just "blocking out" the base of the model or something?
basically it puts a line of filament along the entire "Y" of the bed, and then anotehr all the way back... weird... but if your model is "there" (ie: anywhere near the X side of the bed where the head sweeps along...) well this is not ideal... and the skipto process says "anyting before layer0 is 'cool' don't touch (becuase its usually things like homing and set temps, init/align extruders and so on...)

I'm not sure what to make of this so if you (or anyone) has thoughts and ideas about how to identify and/or deal with this kind of thing I'm open...

I will continue to ponder this ?unique ness?

but also feel free to shoot me more info as to HOW this "3nder3 specific" stuff got in there - if its part of the ender3 setup with cura/config or if its somethign else... that info might help me figure out how to identify and deal...

let me know

**Comment by chrisl300** [comment] 2024-09-07 21:09
I had another failed print last night, that failed on layer 11. Therefore using the previous version, it should have been OK for the printer to do the run-out lines without knocking the model off the base plate, as it was flat enough to go under the X-bar when it was printing the run-out lines.

Unfortunatly what happened was, it printed the run-out lines ok, the part-model slid under the X-bar OK, and then the head crashed into the model as if it were trying to print layer 11 with z=0.

I'm not sure this is going to work unless it can calculate add a code to put the nozzle at the correct height, AFTER it has done the run-out lines and before it resumes printing.

**Comment by chrisl300** [comment] 2024-09-07 21:39
> Okay so 2 things.
> 
> 1. just released a new version that has a few more bells and whistles that MAY make things better generally.

I am fairly new to 3D printing. I did a free training course and got a free printer :)

That scary code was generated from Untimaker Cura, and all I've done is download the program and tell it which printer I have, an Ender 3. The code I sent to you has been nowhere near the printer so it must be from Cura.

As I understand it, it is to get the filament flowing properly before it starts printing the model. Often the lines only start half-way through the first line. Yes it does mean you can't print right to the left edge. These are what I am calling the "run-out lines".

**Comment by awe-source** [comment] 2024-09-07 22:30
Yeah, not surprising. Lots of config and pre-sets have some weird custom code like that... the challenge is trying to figure out how to deal with that.

I wonder if adding some kind of checkbox like ignore all movements prior to skip to layer that will allow you to Cater for "I was watching it and it just failed and so pretty much everything is right and the nozzles already primed" 
vs 
"this failed while I was asleep and I have no idea what state it was in and the filament broke and I've had to change that and clean the nozzle..."

Or maybe it should just blanket ignore movement ... And maybe put in its own purge of 10mm...

Hmmm

**Comment by chrisl300** [comment] 2024-09-07 22:38
Last night, after much ironing my nozzle was clogged and I had to take the hot end apart, so there was a lot of movement already. Although only 11 layers, it was a very complicated and large flat build, so it had taken about 2 hours already. Otherwise I'd just start again.

It is never going to be able to do the run-out lines, if the part-built model it too tall to go under the x-bar.

**Comment by awe-source** [comment] 2024-09-07 22:57
Ok we think that adding two options will do the trick

1. Skip all initialisation mMovement (on by default)

2. Skip z homing (on by default) 

1. Means that there won't be any purge or setup but hopefully the user can do all that stuff to setup things before restarting 

2. Means that it will only find its home for x and y assuming that z is still a known value... which is pretty solid on most printers...

With your z0 problem can you share the gcode again or at least say if the mode was later or zheight as I think one of these may have a weird bug.

Thanks so much

**Comment by awe-source** [comment] 2024-09-08 07:16
If you're able to try again perhaps you will have more success with the latest version 0.1.3

It's has a bunch of changes that hopefully have sensible/useful/logical/self explanatory defaults

**Comment by awe-source** [comment] 2024-09-10 05:40
Failing further feedback I'm going to close this one.
If there's others feel free to reopen or create new issue.

**Closed as completed by awe-source** 2024-09-10 05:40 UTC
